import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import Layout from '@/components/Layout';

import './globals.scss';

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={nunito.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
