export const darkTheme = {
  bg: 'var(--clr-bg-dark-primary)',
  bgLighter: 'var(--clr-bg-dark-secondary)',
  bgInput: 'var(--clr-bg-dark-primary)',
  bgDesignInput: 'var(--clr-bg-dark-secondary)',
  bgLoc: 'var(--clr-bg-dark-tertiary)',
  bgUpload: 'var(--clr-bg-dark-tertiary)',
  bgDesign: 'var(--clr-bg-dark-primary)',
  bgState: 'var(--clr-bg-dark-tertiary)',
  text: 'var(--clr-white)',
  textSoft: 'var(--clr-light-1)',
  textLight: 'var(--clr-white)',
  textNav: 'var(--clr-white)',
  textActive: 'var(--clr-light-1)',
  textNavHov: 'var(--clr-light-2)',
  textSmall: 'var(--clr-text-small-dark)',
  outline: 'var(--clr-outline-dark)',
  caret: 'var(--clr-caret-dark)',
};

export const lightTheme = {
  bg: 'var(--clr-white)',
  bgLighter: 'var(--clr-gray-light-1)',
  bgInput: 'var(--clr-white)',
  bgDesignInput: 'var(--clr-white)',
  bgLoc: 'rgba(204, 126, 252, 0.5)',
  bgUpload: 'var(--clr-gray-light-1)',
  bgDesign: 'var(--clr-gray-light-1)',
  bgState: 'var(--clr-white)',
  text: 'var(--clr-purple-light-1)',
  textSoft: 'inherit',
  textLight: 'var(--clr-gray-dark-3)',
  textNav: 'var(--clr-purple-light-1)',
  textActive: 'var(--clr-purple-dark-2)',
  textNavHov: 'var(--clr-purple-light-2)',
  textSmall: 'var(--clr-text-small-light)',
  outline: 'var(--clr-outline-light)',
  caret: 'var(--clr-caret-light)',
};
